# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WordNet-Similarity
version:      1.04
version_from: lib/WordNet/Similarity.pm
installdirs:  site
requires:
    Text::Similarity:              0.02
    WordNet::QueryData:            1.39

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
